services:
  n8n:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: n8n
    restart: unless-stopped
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_RUNNERS_ENABLED=true
      - NODE_ENV=production
      - N8N_SECURE_COOKIE=false
      - N8N_LOG_LEVEL=debug
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      - PUPPETEER_WEBSOCKET_ENDPOINT=ws://browserless:3000
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n

  browserless:
    image: browserless/chrome
    container_name: browserless

volumes:
  n8n_data:
